// Generated by `mise run supabase:types` once a local/remote Supabase project is available.
// This placeholder mirrors the generated type shape so adapters are type-safe before refresh.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type PublicationStatus = 'draft' | 'pending_review' | 'published' | 'archived';
export type PublicVisibility = 'public' | 'members' | 'private';
export type EventRegistrationMode = 'external' | 'disabled' | 'internal';
export type EventCapacityStatus = 'open' | 'limited' | 'full' | 'waitlist' | 'unknown';
export type RegistrationRequestStatus = 'pending' | 'approved' | 'rejected';

type Table<Row, Insert = Partial<Row>, Update = Partial<Row>> = {
  Row: Row;
  Insert: Insert;
  Update: Update;
  Relationships: [];
};

export interface Database {
  public: {
    Tables: {
      events: Table<{
        id: string;
        slug: string;
        title: string;
        starts_at: string;
        ends_at: string | null;
        location_label: string | null;
        summary: string | null;
        registration_mode: EventRegistrationMode;
        registration_url: string | null;
        registration_label: string | null;
        capacity_status: EventCapacityStatus;
        publication_status: PublicationStatus;
        visibility: PublicVisibility;
        created_at: string;
        updated_at: string;
      }>;
      people: Table<{
        id: string;
        profile_id: string | null;
        company_id: string | null;
        slug: string;
        name: string;
        role: string | null;
        company_name: string | null;
        location_label: string | null;
        founder_context: string | null;
        topics: string[];
        public_directory_consent: boolean;
        publication_status: PublicationStatus;
        visibility: PublicVisibility;
        created_at: string;
        updated_at: string;
      }>;
      companies: Table<{
        id: string;
        slug: string;
        name: string;
        tagline: string | null;
        category: string | null;
        stage: string | null;
        location_label: string | null;
        website_url: string | null;
        publication_status: PublicationStatus;
        visibility: PublicVisibility;
        created_at: string;
        updated_at: string;
      }>;
      registration_requests: Table<{
        id: string;
        name: string;
        email: string;
        company_name: string | null;
        role: string | null;
        founder_context: string | null;
        topics: string[];
        public_directory_consent: boolean;
        status: RegistrationRequestStatus;
        created_at: string;
        reviewed_at: string | null;
        reviewed_by: string | null;
      }>;
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      publication_status: PublicationStatus;
      public_visibility: PublicVisibility;
      event_registration_mode: EventRegistrationMode;
      event_capacity_status: EventCapacityStatus;
      registration_request_status: RegistrationRequestStatus;
    };
    CompositeTypes: Record<string, never>;
  };
}
